In [1]:
import pandas as pd
usgs = pd.read_csv('./USGS Flow/GagesNJ_Height.csv')
usgs

,Unnamed: 0,agency_cd,site_no,datetime,tz_cd,194264_00065,194264_00065_cd,OID_,Field1,REACHCODE,...,FEATUREDET,Measure,Offset,EventType,FLComID,POINT_X,POINT_Y,POINT_Z,POINT_M,COMID
0,0,USGS,1389802,2011-08-30 03:00,EDT,122.54,A,708.0,2203.0,2.030000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,79.85481,0.0,StreamGage,6251048.0,-74.181557,40.915657,0.0,79.85481,6251048.0
1,1,USGS,1403060,2011-08-28 18:00,EDT,41.90,A,490.0,1865.0,2.030000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,68.90423,0.0,StreamGage,9513378.0,-74.548574,40.551601,0.0,68.90423,9513378.0
2,2,USGS,1400500,2011-08-28 16:00,EDT,26.29,A,491.0,2015.0,2.030000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,89.83748,0.0,StreamGage,9513852.0,-74.583119,40.555555,0.0,89.83748,9513852.0
3,3,USGS,1388500,2011-08-29 01:15,EDT,25.24,A,720.0,2466.0,2.030000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,56.37115,0.0,StreamGage,6249470.0,-74.281760,40.969298,0.0,56.37115,6249470.0
4,4,USGS,1446995,2011-08-29 05:00,EDT,25.15,A,565.0,2389.0,2.040000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,86.53518,0.0,StreamGage,2588457.0,-75.203571,40.694496,0.0,86.53518,2588457.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,151,USGS,1379773,2011-08-28 19:45,EDT,3.84,A,692.0,2638.0,2.030000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,13.19529,0.0,StreamGage,6249510.0,-74.539606,40.959444,0.0,13.19529,6249510.0
152,152,USGS,1408750,2011-08-28 10:30,EDT,3.28,A,259.0,1837.0,2.040000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,68.81836,0.0,StreamGage,9455851.0,-74.081926,39.938890,0.0,68.81836,9455851.0
153,153,USGS,1443900,2011-08-28 10:30,EDT,3.22,A,664.0,2567.0,2.040000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,62.34066,0.0,StreamGage,2587723.0,-75.039398,40.981147,0.0,62.34066,2587723.0
154,154,USGS,1466500,2011-08-28 10:45,EDT,2.54,A,246.0,1663.0,2.040000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,0.45271,0.0,StreamGage,4492036.0,-74.505276,39.885006,0.0,0.45271,4499256.0
155,155,USGS,1409110,2011-08-28 06:36,EDT,2.51,A,175.0,1917.0,2.040000e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,43.56923,0.0,StreamGage,9456017.0,-74.182197,39.791170,0.0,43.56923,9456017.0

In [3]:
flow = pd.read_excel('./NWM Flow/all_flows.xlsx')
flow

,COMID,20110827_00_Q,20110827_01_Q,20110827_02_Q,20110827_03_Q,20110827_04_Q,20110827_05_Q,20110827_06_Q,20110827_07_Q,20110827_08_Q,...,20110831_17_Q,20110831_18_Q,20110831_19_Q,20110831_20_Q,20110831_21_Q,20110831_22_Q,20110831_23_Q,fmax,Unnamed: 122,peak_time
0,1748535.0,0.92,0.92,0.92,0.92,0.92,0.93,0.93,0.93,0.93,...,2.21,2.17,2.15,2.12,2.1,2.07,2.05,19.1,30208,20110828_21_Q
1,1748537.0,0.18,0.18,0.19,0.19,0.19,0.19,0.19,0.19,0.19,...,2.84,2.74,2.66,2.59,2.53,2.45,2.38,57.969999,30207,20110828_20_Q
2,1748539.0,0.16,0.16,0.16,0.16,0.16,0.17,0.17,0.17,0.17,...,1.03,1.09,1.1,1.03,1.0,0.95,0.97,20.27,30206,20110828_12_Q
3,1748541.0,1.69,1.7,1.7,1.7,1.7,1.71,1.71,1.71,1.72,...,6.88,6.69,6.51,6.36,6.23,6.13,6.02,131.899997,30205,20110828_12_Q
4,1748543.0,0.66,0.67,0.67,0.68,0.69,0.7,0.7,0.72,0.72,...,3.27,3.24,3.2,3.09,3.04,2.97,2.97,72.239998,30204,20110828_12_Q
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30203,932050173.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.44,5,20110828_03_Q
30204,932060023.0,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,0.28,...,1.93,1.94,1.94,1.95,1.96,1.97,1.97,83.689998,4,20110828_02_Q
30205,932060024.0,0.27,0.26,0.26,0.26,0.26,0.26,0.26,0.26,0.26,...,1.77,1.78,1.78,1.79,1.8,1.81,1.81,81.219998,3,20110828_02_Q
30206,932060025.0,0.28,0.28,0.27,0.27,0.27,0.27,0.27,0.27,0.27,...,1.88,1.89,1.9,1.91,1.92,1.92,1.93,82.689998,2,20110828_02_Q
30207,NaN,20110827_00_Q,20110827_01_Q,20110827_02_Q,20110827_03_Q,20110827_04_Q,20110827_05_Q,20110827_06_Q,20110827_07_Q,20110827_08_Q,...,20110831_17_Q,20110831_18_Q,20110831_19_Q,20110831_20_Q,20110831_21_Q,20110831_22_Q,20110831_23_Q,fmax,2,0

In [6]:
when = flow[['COMID', 'peak_time']]
when

             COMID      peak_time
0        1748535.0  20110828_21_Q
1        1748537.0  20110828_20_Q
2        1748539.0  20110828_12_Q
3        1748541.0  20110828_12_Q
4        1748543.0  20110828_12_Q
...            ...            ...
30203  932050173.0  20110828_03_Q
30204  932060023.0  20110828_02_Q
30205  932060024.0  20110828_02_Q
30206  932060025.0  20110828_02_Q
30207          NaN              0

[30208 rows x 2 columns]

In [7]:
both = usgs.merge(when,on='COMID')
both

,Unnamed: 0,agency_cd,site_no,datetime,tz_cd,194264_00065,194264_00065_cd,OID_,Field1,REACHCODE,...,Measure,Offset,EventType,FLComID,POINT_X,POINT_Y,POINT_Z,POINT_M,COMID,peak_time
0,0,USGS,1389802,2011-08-30 03:00,EDT,122.54,A,708.0,2203.0,2.030000e+12,...,79.85481,0.0,StreamGage,6251048.0,-74.181557,40.915657,0.0,79.85481,6251048.0,20110829_01_Q
1,1,USGS,1403060,2011-08-28 18:00,EDT,41.90,A,490.0,1865.0,2.030000e+12,...,68.90423,0.0,StreamGage,9513378.0,-74.548574,40.551601,0.0,68.90423,9513378.0,20110828_19_Q
2,2,USGS,1400500,2011-08-28 16:00,EDT,26.29,A,491.0,2015.0,2.030000e+12,...,89.83748,0.0,StreamGage,9513852.0,-74.583119,40.555555,0.0,89.83748,9513852.0,20110828_18_Q
3,3,USGS,1388500,2011-08-29 01:15,EDT,25.24,A,720.0,2466.0,2.030000e+12,...,56.37115,0.0,StreamGage,6249470.0,-74.281760,40.969298,0.0,56.37115,6249470.0,20110828_16_Q
4,4,USGS,1446995,2011-08-29 05:00,EDT,25.15,A,565.0,2389.0,2.040000e+12,...,86.53518,0.0,StreamGage,2588457.0,-75.203571,40.694496,0.0,86.53518,2588457.0,20110830_19_Q
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,149,USGS,1409000,2011-08-28 09:45,EDT,4.32,A,255.0,1940.0,2.040000e+12,...,18.62468,0.0,StreamGage,9453855.0,-74.169190,39.867962,0.0,18.62468,9453855.0,20110828_08_Q
148,150,USGS,1396800,2011-08-28 14:30,EDT,4.06,A,569.0,1981.0,2.030000e+12,...,0.00322,0.0,StreamGage,9513994.0,-74.915253,40.639259,0.0,0.00322,9512994.0,20110828_09_Q
149,151,USGS,1379773,2011-08-28 19:45,EDT,3.84,A,692.0,2638.0,2.030000e+12,...,13.19529,0.0,StreamGage,6249510.0,-74.539606,40.959444,0.0,13.19529,6249510.0,20110828_13_Q
150,153,USGS,1443900,2011-08-28 10:30,EDT,3.22,A,664.0,2567.0,2.040000e+12,...,62.34066,0.0,StreamGage,2587723.0,-75.039398,40.981147,0.0,62.34066,2587723.0,20110828_10_Q
151,154,USGS,1466500,2011-08-28 10:45,EDT,2.54,A,246.0,1663.0,2.040000e+12,...,0.45271,0.0,StreamGage,4492036.0,-74.505276,39.885006,0.0,0.45271,4499256.0,20110828_03_Q

In [8]:
both.to_csv('./USGS Flow/GagesNJ_Height_Flow.csv')