Copyright 2021 D Bazzett  
The purpose of this code is to analyze USGS data from this website and convert it into a clean text document, that can then be converted to a csv in excel   
https://waterservices.usgs.gov/rest/IV-Test-Tool.html  

This is the URL to download gage flow data from Hurricane Irene within bounded coordinates  
//waterservices.usgs.gov/nwis/iv/?format=rdb&bBox=-76.390000,38.900000,-73.490000,42.500000&startDT=2011-08-26T00:00-0400&endDT=2011-09-02T00:00-0400&parameterCd=00060&siteStatus=all

In [1]:
import pandas as pd
# data = pd.read_json('./USGS Flow/nwis.waterservices.usgs.gov.json', typ='series', orient='index')
# data

In [2]:
# data.timeSeries

In [3]:
# f = open("./USGS Flow/GageHeight2.txt", "r")
# out = open("./USGS Flow/GageHeight2Notes.txt", 'w')
# for line in f:
# #     if line[0] == 'U':
# #         out.write(line)
#     if line.find('Gage height') != -1:
#         out.write(line)

In [4]:
data = pd.read_csv('./USGS Flow/NJ Stream Gages.csv',infer_datetime_format=True)
data

      agency_cd  site_no          datetime tz_cd  194265_00060 194265_00060_cd
0          USGS  1367690  2011-08-26 00:00   EDT          14.0               A
1          USGS  1367690  2011-08-26 00:15   EDT          14.0               A
2          USGS  1367690  2011-08-26 00:30   EDT          14.4               A
3          USGS  1367690  2011-08-26 00:45   EDT          14.4               A
4          USGS  1367690  2011-08-26 01:00   EDT          14.4               A
...         ...      ...               ...   ...           ...             ...
78937      USGS  1482500  2011-09-01 23:00   EDT          17.7               A
78938      USGS  1482500  2011-09-01 23:15   EDT          17.7               A
78939      USGS  1482500  2011-09-01 23:30   EDT          17.7               A
78940      USGS  1482500  2011-09-01 23:45   EDT          17.7               A
78941      USGS  1482500  2011-09-02 00:00   EDT          17.7               A

[78942 rows x 6 columns]

In [5]:
data.dtypes

agency_cd           object
site_no              int64
datetime            object
tz_cd               object
194265_00060       float64
194265_00060_cd     object
dtype: object

In [6]:
for site in data.site_no.unique():
    print(site)

1367690
1367800
1377000
1377370
1377500
1378500
1379000
1379500
1379530
1379699
1379773
1379780
1379868
1380500
1381000
1381400
1381500
1381800
1381900
1382170
1382210
1382270
1382385
1382500
1382800
1383500
1384500
1386000
1387000
1387500
1388000
1388500
1389500
1389550
1389890
1390450
1390500
1391000
1391500
1392500
1393450
1394500
1395000
1396091
1396190
1396500
1396582
1396660
1396800
1397000
1398000
1398500
1398900
1399100
1399500
1399670
1400000
1400500
1401000
1401650
1402000
1403060
1403150
1403400
1403540
1403900
1405030
1405400
1406050
1407290
1407500
1407705
1407760
1408000
1408029
1408043
1408120
1408151
1408500
1409000
1409210
1409280
1409400
1409810
1410000
1410150
1410784
1410820
1411000
1411300
1411456
1411500
1412800
1439800
1440000
1443280
1443500
1443900
1445000
1445500
1446000
1446500
1455090
1455500
1457000
1460440
1460880
1461300
1463500
1463620
1463740
1464000
1464500
1465850
1466500
1466900
1467000
1467081
1467150
1475001
1477120
1482500

In [7]:
maxflow = pd.DataFrame(data.site_no.unique(), columns=['site'])
maxflow['flow'] = ''
maxflow

        site flow
0    1367690
1    1367800
2    1377000
3    1377370
4    1377500
..       ...  ...
117  1467081
118  1467150
119  1475001
120  1477120
121  1482500

[122 rows x 2 columns]

In [8]:
for site in maxflow.site:
    subset = data.loc[data.site_no==site]
    maxflow.flow.loc[maxflow.site == site] = subset['194265_00060'].max()

C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
C:\Users\David\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [9]:
maxflow

        site  flow
0    1367690   913
1    1367800  2750
2    1377000  4660
3    1377370  3500
4    1377500  4630
..       ...   ...
117  1467081  1280
118  1467150  2910
119  1475001   874
120  1477120  5510
121  1482500   196

[122 rows x 2 columns]

In [12]:
usgs = pd.read_csv('./USGS Flow/Gages.csv')
usgs

,EVENTDATE,REACHCODE,REACHSMDAT,REACHRESOL,FEATURECOM,FEATURECLA,SOURCE_ORI,SOURCE_DAT,SOURCE_FEA,FEATUREDET,Measure,Offset,EventType,FLComID,POINT_X,POINT_Y,POINT_Z,POINT_M
0,2014-12-04 00:00,1.100010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,1.206900e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,45.31563,0,StreamGage,7712706,-73.069576,41.673986,0,45.31563
1,2014-12-04 00:00,1.100010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,1.206000e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,15.86635,0,StreamGage,7713630,-73.063803,41.704479,0,15.86635
2,2014-12-04 00:00,1.090000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,1.105917e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,9.65026,0,StreamGage,5878903,-70.838619,41.662913,0,9.65026
3,2014-12-04 00:00,1.100010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,1.205500e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,45.47307,0,StreamGage,7718288,-73.167566,41.383470,0,45.47307
4,2014-12-04 00:00,1.090000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,1.109200e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,69.19802,0,StreamGage,6129557,-71.254757,41.879573,0,69.19802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28159,2012-12-06 00:00,2.101000e+13,2012-02-27 00:00,High,0,0,United States Geological Survey (USGS),National Water Information System (NWIS),1.802240e+14,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,83.12687,0,StreamGage,800040636,-65.919321,18.038005,0,83.12687
28160,2012-12-06 00:00,2.101000e+13,2012-02-27 00:00,High,0,0,United States Geological Survey (USGS),National Water Information System (NWIS),1.802030e+14,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,96.73209,0,StreamGage,800025568,-65.906174,18.033222,0,96.73209
28161,2012-12-06 00:00,2.101000e+13,2012-02-27 00:00,High,0,0,United States Geological Survey (USGS),National Water Information System (NWIS),5.009121e+07,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,81.30001,0,StreamGage,800036345,-65.905677,17.996457,0,81.30001
28162,2014-12-04 00:00,4.040000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,4.087047e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,33.61331,0,StreamGage,12163786,-88.027910,43.221473,0,33.61331
28163,2014-12-04 00:00,2.020000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",,1.318500e+06,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,57.59153,0,StreamGage,22307227,-73.842525,43.315098,0,57.59153

In [13]:
usgs2=usgs[['SOURCE_FEA', 'FLComID']]
usgs2

         SOURCE_FEA    FLComID
0      1.206900e+06    7712706
1      1.206000e+06    7713630
2      1.105917e+06    5878903
3      1.205500e+06    7718288
4      1.109200e+06    6129557
...             ...        ...
28159  1.802240e+14  800040636
28160  1.802030e+14  800025568
28161  5.009121e+07  800036345
28162  4.087047e+06   12163786
28163  1.318500e+06   22307227

[28164 rows x 2 columns]

In [15]:
usgs2.dtypes

SOURCE_FEA    float64
FLComID         int64
dtype: object

In [16]:
maxflow2 = maxflow.merge(usgs2, left_on='site', right_on='SOURCE_FEA')
maxflow2

        site   flow  SOURCE_FEA  FLComID
0    1367800   2750   1367800.0  6203098
1    1377000   4660   1377000.0  6248392
2    1377370   3500   1377370.0  6245972
3    1377500   4630   1377500.0  6249408
4    1378500  10500   1378500.0  6249556
..       ...    ...         ...      ...
107  1467081   1280   1467081.0  4495672
108  1467150   2910   1467150.0  4494690
109  1475001    874   1475001.0  4495272
110  1477120   5510   1477120.0  4495818
111  1482500    196   1482500.0  9481992

[112 rows x 4 columns]

In [17]:
nwm = pd.read_csv('./USGS Flow/NWM_maxflow.csv')
nwm

           COMID          Q         H
0        2583257  35.789999  1.971688
1        2583289   7.090000  0.344949
2        2583307  19.600000  0.437739
3        2583311   4.280000  0.225530
4        2583317  75.899998  7.093974
...          ...        ...       ...
13667  932050087   5.710000  0.043462
13668  932050113   6.290000  0.321576
13669  932050133   6.650000  0.176893
13670  932050166   3.560000  0.456918
13671  932050172  35.809999  0.460424

[13672 rows x 3 columns]

In [18]:
maxflow2 = maxflow2.merge(nwm, left_on='FLComID', right_on='COMID')
maxflow2

       site  flow  SOURCE_FEA  FLComID    COMID           Q         H
0   1377000  4660   1377000.0  6248392  6248392  292.879994  6.060012
1   1377500  4630   1377500.0  6249408  6249408  238.019995  2.949205
2   1379000  2120   1379000.0  6250860  6250860  152.079997  1.907942
3   1379500  2620   1379500.0  6250836  6250836  226.129995  2.728292
4   1379530  5940   1379530.0  6250812  6250812   68.159998  1.011513
..      ...   ...         ...      ...      ...         ...       ...
86  1467000  2400   1467000.0  4491898  4491898  190.239996  1.965172
87  1467081  1280   1467081.0  4495672  4495672   81.809998  5.059443
88  1467150  2910   1467150.0  4494690  4494690  118.719997  5.294272
89  1475001   874   1475001.0  4495272  4495272   75.199998  0.915468
90  1477120  5510   1477120.0  4495818  4495818   99.269998  0.825550

[91 rows x 7 columns]

In [19]:
maxflow2.to_csv('./USGS Flow/Gage&NWM.csv')

In [3]:
ht = pd.read_csv('./USGS Flow/GageHeight.csv')
ht

,agency_cd,site_no,datetime,tz_cd,194264_00065,194264_00065_cd
0,USGS,1367690,2011-08-26 00:00,EDT,1.74,A
1,USGS,1367690,2011-08-26 00:15,EDT,1.74,A
2,USGS,1367690,2011-08-26 00:30,EDT,1.75,A
3,USGS,1367690,2011-08-26 00:45,EDT,1.75,A
4,USGS,1367690,2011-08-26 01:00,EDT,1.75,A
...,...,...,...,...,...,...
109165,USGS,1482500,2011-09-01 09:15,EDT,11.15,A
109166,USGS,1482500,2011-09-01 09:30,EDT,11.15,A
109167,USGS,1482500,2011-09-01 09:45,EDT,11.15,A
109168,USGS,1482500,2011-09-01 10:00,EDT,11.15,A
109169,USGS,1482500,2011-09-01 10:15,EDT,11.15,A

In [6]:
ht = ht.sort_values(by='194264_00065',ascending=False)
ht

      agency_cd  site_no          datetime tz_cd  194264_00065 194264_00065_cd
29261      USGS  1389802  2011-08-30 03:00   EDT        122.54               A
29257      USGS  1389802  2011-08-30 02:00   EDT        122.54               A
29260      USGS  1389802  2011-08-30 02:45   EDT        122.54               A
29265      USGS  1389802  2011-08-30 04:00   EDT        122.54               A
29263      USGS  1389802  2011-08-30 03:30   EDT        122.54               A
...         ...      ...               ...   ...           ...             ...
67853      USGS  1408050  2011-08-29 03:06   EDT         -3.04               A
67852      USGS  1408050  2011-08-29 03:00   EDT         -3.05               A
67855      USGS  1408050  2011-08-29 03:18   EDT         -3.06               A
67851      USGS  1408050  2011-08-29 02:54   EDT         -3.10               A
67854      USGS  1408050  2011-08-29 03:12   EDT         -3.13               A

[109170 rows x 6 columns]

In [8]:
ht2 = ht.drop_duplicates(subset='site_no')
ht2

,agency_cd,site_no,datetime,tz_cd,194264_00065,194264_00065_cd
29261,USGS,1389802,2011-08-30 03:00,EDT,122.54,A
56091,USGS,1403060,2011-08-28 18:00,EDT,41.90,A
51430,USGS,1400500,2011-08-28 16:00,EDT,26.29,A
25120,USGS,1388500,2011-08-29 01:15,EDT,25.24,A
91119,USGS,1446995,2011-08-29 05:00,EDT,25.15,A
...,...,...,...,...,...,...
6988,USGS,1379773,2011-08-28 19:45,EDT,3.84,A
71380,USGS,1408750,2011-08-28 10:30,EDT,3.28,A
87682,USGS,1443900,2011-08-28 10:30,EDT,3.22,A
104310,USGS,1466500,2011-08-28 10:45,EDT,2.54,A
73692,USGS,1409110,2011-08-28 06:36,EDT,2.51,A

In [9]:
nj = pd.read_csv('./USGS Flow/GagesNJ_HUC.csv')
nj

,OID_,Field1,EVENTDATE,REACHCODE,REACHSMDAT,REACHRESOL,FEATURECOM,FEATURECLA,SOURCE_ORI,SOURCE_DAT,...,FEATUREDET,Measure,Offset,EventType,FLComID,POINT_X,POINT_Y,POINT_Z,POINT_M,RASTERVALU
0,1,1369,2014-12-04 00:00:00,2.060000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,30.84248,0,StreamGage,4766870,-76.072273,39.040168,0,30.84248,NaN
1,2,1452,2014-12-04 00:00:00,2.060000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,32.89288,0,StreamGage,4766680,-76.055163,39.054286,0,32.89288,NaN
2,3,1500,2014-12-04 00:00:00,2.060000e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,37.50628,0,StreamGage,4768920,-76.109346,38.964475,0,37.50628,NaN
3,4,1403,2014-12-04 00:00:00,2.060010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,76.56757,0,StreamGage,9407582,-75.942725,38.966743,0,76.56757,NaN
4,5,1392,2014-12-04 00:00:00,2.060010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,4.25223,0,StreamGage,9407484,-75.785372,38.997196,0,4.25223,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,1138,2937,2014-12-04 00:00:00,2.020010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,21.39716,0,StreamGage,6188198,-73.982208,42.488184,0,21.39716,NaN
1138,1139,2747,2014-12-04 00:00:00,2.020010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,61.37064,0,StreamGage,6188216,-73.810065,42.439672,0,61.37064,NaN
1139,1140,3018,2014-12-04 00:00:00,2.020010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,11.13148,0,StreamGage,6188948,-73.743618,42.329592,0,11.13148,NaN
1140,1141,3035,2014-12-04 00:00:00,2.020010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,11.34027,0,StreamGage,6188346,-73.575638,42.352435,0,11.34027,NaN
1141,1142,3054,2014-12-04 00:00:00,2.020010e+12,NaN,Medium,0,0,"USGS, Water Resources Division",NaN,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,40.52875,0,StreamGage,6188352,-73.574604,42.347564,0,40.52875,NaN

In [10]:
ht2 = ht2.merge(nj, left_on='site_no', right_on='SOURCE_FEA',how='left')
ht2

,agency_cd,site_no,datetime,tz_cd,194264_00065,194264_00065_cd,OID_,Field1,EVENTDATE,REACHCODE,...,FEATUREDET,Measure,Offset,EventType,FLComID,POINT_X,POINT_Y,POINT_Z,POINT_M,RASTERVALU
0,USGS,1389802,2011-08-30 03:00,EDT,122.54,A,708.0,2203.0,2014-12-04 00:00:00,2.030100e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,79.85481,0.0,StreamGage,6251048.0,-74.181557,40.915657,0.0,79.85481,6251048.0
1,USGS,1403060,2011-08-28 18:00,EDT,41.90,A,490.0,1865.0,2014-12-04 00:00:00,2.030110e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,68.90423,0.0,StreamGage,9513378.0,-74.548574,40.551601,0.0,68.90423,9513378.0
2,USGS,1400500,2011-08-28 16:00,EDT,26.29,A,491.0,2015.0,2014-12-04 00:00:00,2.030110e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,89.83748,0.0,StreamGage,9513852.0,-74.583119,40.555555,0.0,89.83748,9513852.0
3,USGS,1388500,2011-08-29 01:15,EDT,25.24,A,720.0,2466.0,2014-12-04 00:00:00,2.030100e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,56.37115,0.0,StreamGage,6249470.0,-74.281760,40.969298,0.0,56.37115,6249470.0
4,USGS,1446995,2011-08-29 05:00,EDT,25.15,A,565.0,2389.0,2014-12-04 00:00:00,2.040110e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,86.53518,0.0,StreamGage,2588457.0,-75.203571,40.694496,0.0,86.53518,2588457.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,USGS,1379773,2011-08-28 19:45,EDT,3.84,A,692.0,2638.0,2014-12-04 00:00:00,2.030100e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,13.19529,0.0,StreamGage,6249510.0,-74.539606,40.959444,0.0,13.19529,6249510.0
152,USGS,1408750,2011-08-28 10:30,EDT,3.28,A,259.0,1837.0,2014-12-04 00:00:00,2.040300e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,68.81836,0.0,StreamGage,9455851.0,-74.081926,39.938890,0.0,68.81836,9455851.0
153,USGS,1443900,2011-08-28 10:30,EDT,3.22,A,664.0,2567.0,2014-12-04 00:00:00,2.040110e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,62.34066,0.0,StreamGage,2587723.0,-75.039398,40.981147,0.0,62.34066,2587723.0
154,USGS,1466500,2011-08-28 10:45,EDT,2.54,A,246.0,1663.0,2014-12-04 00:00:00,2.040200e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,0.45271,0.0,StreamGage,4492036.0,-74.505276,39.885006,0.0,0.45271,4499256.0
155,USGS,1409110,2011-08-28 06:36,EDT,2.51,A,175.0,1917.0,2014-12-04 00:00:00,2.040300e+12,...,http://waterdata.usgs.gov/nwis/nwisman/?site_n...,43.56923,0.0,StreamGage,9456017.0,-74.182197,39.791170,0.0,43.56923,9456017.0

In [11]:
ht2.to_csv('./USGS Flow/GagesNJ_Height.csv')